version: '3.9'

services:
  postgres:
    image: postgres:16.4-alpine
    container_name: uni-app-postgres
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    command:
      "postgres -c 'max_connections=500'"
    environment:
      - POSTGRES_PASSWORD=111111
      - POSTGRES_USER=postgres
      - POSTGRES_DB=univapp_db

    