default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres  
  password: 111111
  host: localhost
  port: 5432

development:
  <<: *default
  database: univapp_db

test:
  <<: *default
  database: univapp_test

production:
  <<: *default
  database: univapp_production
