default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres  
  password: 11111111
  host: /cloudsql/dockeruniversitytf:us-central1:uni-app
  port: 5432

development:
  <<: *default
  username: postgres  
  password: 11111111
  database: univapp_db

test:
  <<: *default
  username: postgres  
  password: 11111111
  database: univapp_test

production:
  <<: *default
  port: 5432
  adapter: postgresql
  encoding: unicode
  database: uni_app
  username: postgres
  password: 11111111
  host: /cloudsql/dockeruniversitytf:us-central1:uni-app
